using System.Net;
using System.Security;
using System.Security.Claims;
using System.Security.Cryptography;
using System.Text;
using Microsoft.AspNetCore.Antiforgery;
static class SuiteAdminPanel
{
 const string Read="suite.read",Issue="suite.activation.issue",Export="suite.audit.export";
 public static void Map(WebApplication app)
 {
  app.MapGet("/admin/suite",async(HttpContext c,IAntiforgery a,SuiteAdminBff b,CancellationToken ct)=>{if(!Has(c,Read))return Results.Forbid();try{var id=EnvId();var s=await b.StatusAsync(id,ct);return Html(Page(s,a.GetAndStoreTokens(c).RequestToken??"",c.Request.Query["error"].ToString()));}catch(HttpRequestException){return Html(Unavailable(),503);}}).RequireAuthorization();
  app.MapGet("/admin/suite/issued",()=>Results.Redirect("/admin/suite")).RequireAuthorization();
  app.MapPost("/admin/suite/actions/issue-otp",async(HttpContext c,IAntiforgery a,OnlineAdminConfiguration admin,SuiteAdminBff b,SuiteIssueGuard guard,CancellationToken ct)=>{if(!Has(c,Issue))return Results.Forbid();try{await a.ValidateRequestAsync(c);var f=await c.Request.ReadFormAsync(ct);if(!AdminPasswordHash.Verify(admin.PasswordHash,Required(f,"adminPassword")))throw new SecurityException();var id=Required(f,"licenseId");var device=Required(f,"deviceId");if(!Fixed(id,Required(f,"confirmLicenseId"))||!Fixed(device,Required(f,"confirmDeviceId"))||!Fixed(id,EnvId()))throw new SecurityException();var key=(c.User.Identity?.Name??"unknown")+'\0'+id+'\0'+(c.Connection.RemoteIpAddress?.ToString()??"unknown");if(!guard.Allow(key))return Results.Redirect("/admin/suite?error=RATE_LIMIT");var status=await b.StatusAsync(id,ct);if(!Fixed(status.DeviceId,device))throw new SecurityException();var issued=await b.IssueAsync(id,device,c.User.Identity?.Name??"unknown",Convert.ToHexString(RandomNumberGenerator.GetBytes(16)).ToLowerInvariant(),ct);c.Response.Headers.CacheControl="no-store, no-cache, must-revalidate";c.Response.Headers.Pragma="no-cache";return Html(Otp(issued));}catch(Exception ex)when(ex is SecurityException or AntiforgeryValidationException or HttpRequestException){return Results.Redirect("/admin/suite?error=OPERATION_DENIED");}}).RequireAuthorization();
  app.MapGet("/admin/suite/export/audit.csv",async(HttpContext c,SuiteAdminBff b,CancellationToken ct)=>{if(!Has(c,Export))return Results.Forbid();try{return Results.File(await b.AuditAsync(ct),"text/csv; charset=utf-8","turborama-suite-otp-audit.csv");}catch(HttpRequestException){return Results.StatusCode(503);}}).RequireAuthorization();
 }
 static bool Has(HttpContext c,string p)=>c.User.HasClaim("permission",p);
 static string EnvId()=>(Environment.GetEnvironmentVariable("TURBORAMA_SUITE_LICENSE_ID")??"").Trim();
 static string Required(IFormCollection f,string n){var v=f[n].ToString();if(v.Length is <1 or >1024||v.Any(char.IsControl))throw new SecurityException();return v;}
 static bool Fixed(string a,string b){var x=Encoding.UTF8.GetBytes(a);var y=Encoding.UTF8.GetBytes(b);try{return x.Length==y.Length&&CryptographicOperations.FixedTimeEquals(x,y);}finally{CryptographicOperations.ZeroMemory(x);CryptographicOperations.ZeroMemory(y);}}
 static IResult Html(string h,int code=200)=>Results.Content(h,"text/html; charset=utf-8",Encoding.UTF8,code);
 static string E(string? v)=>WebUtility.HtmlEncode(v??"");
 static string Shell(string title,string body)=>"<!doctype html><html lang=pt-BR><head><meta charset=utf-8><meta name=viewport content='width=device-width,initial-scale=1'><title>"+E(title)+"</title><link rel=stylesheet href=/admin/assets/admin.css></head><body><main class=shell><header class=top><div><span class=eyebrow>LZ GAMES / TURBORAMA</span><h1>Central de licenças</h1></div><nav class=top-actions><a class='button ghost' href=/admin>PIX</a><a class='button primary' href=/admin/suite>SUITE</a></nav></header>"+body+"</main></body></html>";
 static string Page(SuiteAdminStatus s,string token,string error)=>Shell("TurboRama SUITE","<section class=scope-banner><div><span class=eyebrow>TURBORAMA SUITE</span><h2>Emissor de ativação</h2><p>Canal isolado por socket Unix. O código aparece uma única vez.</p></div><span class='pill on'>"+E(s.Status)+"</span></section>"+(error.Length>0?"<div class='notice danger'>Operação recusada: "+E(error)+"</div>":"")+"<section class=panel><div class=license-facts><div><span>Licença</span><strong>"+E(s.LicenseId)+"</strong></div><div><span>Máquina esperada</span><strong>"+E(s.DeviceId)+"</strong></div><div><span>Dispositivos ativos</span><strong>"+s.ActiveDevices+"</strong></div><div><span>OTP</span><strong>"+(s.OtpIssued?"EMITIDO":"NÃO EMITIDO")+"</strong></div></div><form method=post action=/admin/suite/actions/issue-otp class=grid-form><input type=hidden name=__RequestVerificationToken value='"+E(token)+"'><input type=hidden name=licenseId value='"+E(s.LicenseId)+"'><input type=hidden name=deviceId value='"+E(s.DeviceId)+"'><label>Confirme a licença<input name=confirmLicenseId required autocomplete=off></label><label>Confirme a máquina<input name=confirmDeviceId required autocomplete=off></label><label>Confirme sua senha<input type=password name=adminPassword required autocomplete=new-password></label><button class=primary>Emitir OTP de 15 minutos</button></form><p class=muted>A emissão será recusada se houver máquina ativa, OTP válido ou divergência de identidade.</p><a class='button ghost' href=/admin/suite/export/audit.csv>Exportar auditoria SUITE</a></section>");
 static string Otp(SuiteOtpResult x)=>Shell("OTP SUITE","<section class=login><div class=login-card><span class=eyebrow>USO ÚNICO / TURBORAMA SUITE</span><h1>OTP de ativação</h1><p>Não será mostrado novamente. Expira em "+E(x.ExpiresAt.ToString("u"))+".</p><code class=activation id=activation-code>"+E(x.Otp)+"</code><div class=activation-actions><button type=button onclick=\"navigator.clipboard.writeText(document.getElementById('activation-code').textContent)\">Copiar</button><a class='button primary' href=/admin/suite>Ocultar e voltar</a></div><script>history.replaceState(null,'','/admin/suite/issued')</script></div></section>");
 static string Unavailable()=>Shell("SUITE indisponível","<section class='panel empty-state'><h1>Emissor SUITE indisponível</h1><p>Nenhuma emissão foi realizada.</p><a class='button ghost' href=/admin>Voltar ao PIX</a></section>");
}
