BEGIN;
SET LOCAL lock_timeout='5s'; SET LOCAL statement_timeout='30s';
SELECT pg_advisory_xact_lock(hashtextextended('suite:020_device_inventory_r25',0));
CREATE TABLE suite.suite_device_inventory_challenges(
 challenge_id char(64) PRIMARY KEY CHECK(challenge_id ~ '^[0-9a-f]{64}$'), schema_version smallint NOT NULL CHECK(schema_version=1), product_id varchar(64) NOT NULL CHECK(product_id='TURBORAMA_SUITE'), license_id varchar(64) NOT NULL, device_id char(64) NOT NULL, session_id char(64) NOT NULL, action varchar(32) NOT NULL CHECK(action='device.inventory'), inventory_hash char(64) NOT NULL CHECK(inventory_hash ~ '^[0-9a-f]{64}$'), nonce varchar(128) NOT NULL, issued_at timestamptz NOT NULL, expires_at timestamptz NOT NULL, consumed_at timestamptz, correlation_id varchar(64) NOT NULL, technical_result varchar(32), FOREIGN KEY(license_id,device_id) REFERENCES suite.suite_devices(license_id,device_id), FOREIGN KEY(session_id) REFERENCES suite.suite_sessions(session_id), CHECK(expires_at>issued_at));
CREATE INDEX ix_suite_inventory_challenge_expiry ON suite.suite_device_inventory_challenges(expires_at) WHERE consumed_at IS NULL;
CREATE INDEX ix_suite_inventory_challenge_device ON suite.suite_device_inventory_challenges(license_id,device_id,issued_at DESC);
CREATE TABLE suite.suite_device_inventory(
 license_id varchar(64) NOT NULL, device_id char(64) NOT NULL, schema_version smallint NOT NULL CHECK(schema_version=1), inventory_hash char(64) NOT NULL CHECK(inventory_hash ~ '^[0-9a-f]{64}$'), motherboard_fingerprint char(64) NOT NULL CHECK(motherboard_fingerprint ~ '^[0-9a-f]{64}$'), baseboard_manufacturer varchar(128) NOT NULL, baseboard_product varchar(128) NOT NULL, baseboard_version varchar(128) NOT NULL, baseboard_serial_cipher bytea NOT NULL, baseboard_serial_masked varchar(128) NOT NULL, system_manufacturer varchar(128) NOT NULL, system_model varchar(128) NOT NULL, system_uuid_cipher bytea NOT NULL, system_uuid_masked varchar(64) NOT NULL, bios_manufacturer varchar(128) NOT NULL, bios_version varchar(128) NOT NULL, os_name varchar(128) NOT NULL, os_version varchar(64) NOT NULL, architecture varchar(8) NOT NULL CHECK(architecture IN('X64','X86','ARM64','ARM')), client_version varchar(64) NOT NULL, source varchar(32) NOT NULL CHECK(source IN('CIM','REGISTRY_FALLBACK','CIM_AND_REGISTRY')), collected_at_unix_seconds bigint NOT NULL CHECK(collected_at_unix_seconds>0), comparison_status varchar(32) NOT NULL CHECK(comparison_status IN('MATCH','ENRICHED','NON_IDENTITY_CHANGE','INCONCLUSIVE','PROBABLE_BOARD_CHANGE')), comparison_confidence varchar(16) NOT NULL CHECK(comparison_confidence IN('NONE','LOW','MEDIUM','HIGH')), received_at timestamptz NOT NULL DEFAULT clock_timestamp(), updated_at timestamptz NOT NULL DEFAULT clock_timestamp(), PRIMARY KEY(license_id,device_id), FOREIGN KEY(license_id,device_id) REFERENCES suite.suite_devices(license_id,device_id));
CREATE TABLE suite.suite_device_inventory_events(
 event_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, license_id varchar(64) NOT NULL, device_id char(64) NOT NULL, session_id char(64) NOT NULL, inventory_hash char(64) NOT NULL CHECK(inventory_hash ~ '^[0-9a-f]{64}$'), motherboard_fingerprint char(64) NOT NULL CHECK(motherboard_fingerprint ~ '^[0-9a-f]{64}$'), schema_version smallint NOT NULL CHECK(schema_version=1), baseboard_manufacturer varchar(128) NOT NULL, baseboard_product varchar(128) NOT NULL, baseboard_version varchar(128) NOT NULL, baseboard_serial_cipher bytea NOT NULL, baseboard_serial_masked varchar(128) NOT NULL, system_manufacturer varchar(128) NOT NULL, system_model varchar(128) NOT NULL, system_uuid_cipher bytea NOT NULL, system_uuid_masked varchar(64) NOT NULL, bios_manufacturer varchar(128) NOT NULL, bios_version varchar(128) NOT NULL, os_name varchar(128) NOT NULL, os_version varchar(64) NOT NULL, architecture varchar(8) NOT NULL, client_version varchar(64) NOT NULL, source varchar(32) NOT NULL, collected_at_unix_seconds bigint NOT NULL, comparison_status varchar(32) NOT NULL, comparison_confidence varchar(16) NOT NULL, received_at timestamptz NOT NULL DEFAULT clock_timestamp(), correlation_id varchar(64) NOT NULL, UNIQUE(license_id,device_id,inventory_hash), FOREIGN KEY(license_id,device_id) REFERENCES suite.suite_devices(license_id,device_id));
CREATE INDEX ix_suite_inventory_events_device ON suite.suite_device_inventory_events(license_id,device_id,received_at DESC);
CREATE TABLE suite.suite_machine_change_reviews(
 review_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, license_id varchar(64) NOT NULL, device_id char(64) NOT NULL, baseline_event_id bigint NOT NULL REFERENCES suite.suite_device_inventory_events(event_id), candidate_event_id bigint NOT NULL REFERENCES suite.suite_device_inventory_events(event_id), status varchar(16) NOT NULL DEFAULT 'PENDING' CHECK(status IN('PENDING','APPROVED','REJECTED','CANCELED')), reason_codes text[] NOT NULL, confidence varchar(16) NOT NULL CHECK(confidence IN('MEDIUM','HIGH')), request_id char(64) NOT NULL UNIQUE, requested_at timestamptz NOT NULL DEFAULT clock_timestamp(), decided_at timestamptz, decided_by varchar(128), decision_reason varchar(512), FOREIGN KEY(license_id,device_id) REFERENCES suite.suite_devices(license_id,device_id));
CREATE UNIQUE INDEX ux_suite_inventory_review_pending ON suite.suite_machine_change_reviews(license_id,device_id,candidate_event_id) WHERE status='PENDING';
CREATE INDEX ix_suite_inventory_review_status ON suite.suite_machine_change_reviews(status,requested_at DESC);
CREATE TABLE suite.suite_device_presence(
 license_id varchar(64) NOT NULL,device_id char(64) NOT NULL,state varchar(16) NOT NULL CHECK(state IN('UNKNOWN','ONLINE','OFFLINE')),
 online_until timestamptz,last_transition_at timestamptz NOT NULL DEFAULT clock_timestamp(),last_notified_at timestamptz,
 updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),PRIMARY KEY(license_id,device_id),
 FOREIGN KEY(license_id,device_id) REFERENCES suite.suite_devices(license_id,device_id));
CREATE TABLE suite.suite_connection_notification_outbox(
 event_id uuid PRIMARY KEY,event_key varchar(256) NOT NULL UNIQUE,event_type varchar(64) NOT NULL CHECK(event_type='device.connected'),
 license_id varchar(64) NOT NULL,device_id char(64) NOT NULL,connected_at timestamptz NOT NULL,status varchar(16) NOT NULL DEFAULT 'PENDING' CHECK(status IN('PENDING','LEASED','SENT','SKIPPED','DEAD')),
 attempts integer NOT NULL DEFAULT 0,next_attempt_at timestamptz NOT NULL DEFAULT clock_timestamp(),lease_until timestamptz,
 last_error_code varchar(64),created_at timestamptz NOT NULL DEFAULT clock_timestamp(),completed_at timestamptz,
 FOREIGN KEY(license_id,device_id) REFERENCES suite.suite_devices(license_id,device_id));
CREATE INDEX ix_suite_connection_outbox_work ON suite.suite_connection_notification_outbox(status,next_attempt_at) WHERE status IN('PENDING','LEASED');
GRANT SELECT,INSERT,UPDATE ON suite.suite_device_inventory_challenges,suite.suite_device_inventory,suite.suite_device_inventory_events,suite.suite_machine_change_reviews TO "turborama-suite";
GRANT USAGE,SELECT ON SEQUENCE suite.suite_device_inventory_events_event_id_seq,suite.suite_machine_change_reviews_review_id_seq TO "turborama-suite";
GRANT SELECT,INSERT,UPDATE ON suite.suite_device_presence,suite.suite_connection_notification_outbox TO "turborama-suite";
GRANT SELECT,UPDATE ON suite.suite_connection_notification_outbox TO "turborama-suite-admin";
GRANT SELECT,UPDATE ON suite.suite_device_inventory,suite.suite_device_inventory_events,suite.suite_machine_change_reviews TO "turborama-suite-admin";
INSERT INTO suite.schema_migrations(version) VALUES('020_suite_device_inventory_r25') ON CONFLICT(version) DO NOTHING;
COMMIT;
