<Project>
 <PropertyGroup Condition="'$(MSBuildProjectName)' == 'StationOnline.Tests' or '$(MSBuildProjectName)' == 'HttpTests'">
  <BaseIntermediateOutputPath>obj/$(MSBuildProjectName)/</BaseIntermediateOutputPath>
  <OutputPath>bin/$(MSBuildProjectName)/$(Configuration)/</OutputPath>
 </PropertyGroup>
</Project>
