<Project Sdk="Microsoft.NET.Sdk.Web"><PropertyGroup><TargetFramework>net8.0</TargetFramework><OutputType>Exe</OutputType><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><TreatWarningsAsErrors>true</TreatWarningsAsErrors><EnableDefaultCompileItems>false</EnableDefaultCompileItems><BaseIntermediateOutputPath>obj/Http/</BaseIntermediateOutputPath><OutputPath>bin/Http/</OutputPath></PropertyGroup><ItemGroup><Compile Include="HttpTests.cs"/><ProjectReference Include="../../../src/TurboRamaSuiteOnlineServer/TurboRamaSuiteOnlineServer.csproj"/></ItemGroup></Project>
