using System.Security.Cryptography;
namespace TurboRamaSuiteAdminServer.Safety;
public sealed record JournalHighWater(string LicenseId,long Sequence,long Generation,string ChainDigest,bool Linearizable,bool ContinuityValid);
public sealed record JournalCommand(string Scope,string RequestId,string RequestDigest,string LicenseId,string Action,long ExpectedSequence,long ExpectedGeneration,string StateDigest,IReadOnlyDictionary<string,string> OpaqueReferences);
public sealed record JournalAppendResult(long Sequence,long Generation,string EventDigest,string ResultDigest,bool AlreadyApplied);
public interface IExternalLifecycleJournal{Task<JournalHighWater> ReadLinearizableAsync(string licenseId,CancellationToken ct);Task<JournalAppendResult?> FindByRequestAsync(string scope,string requestId,CancellationToken ct);Task<JournalAppendResult> ConditionalAppendAsync(JournalCommand command,CancellationToken ct);}
public sealed record RestoreGateState(bool Open,string DatabaseIncarnation,string RestoreEpoch,long JournalCheckpoint,bool Authentic);
public interface IRestoreGateReader{Task<RestoreGateState> ReadAuthoritativeAsync(CancellationToken ct);}
public static class ExternalAuthorizationInterlock{public static void RequireAllow(RestoreGateState gate,string databaseIncarnation,string databaseRestoreEpoch,long appliedJournalSequence,JournalHighWater journal){if(!gate.Authentic||!gate.Open||gate.DatabaseIncarnation!=databaseIncarnation||gate.RestoreEpoch!=databaseRestoreEpoch||!journal.Linearizable||!journal.ContinuityValid||gate.JournalCheckpoint!=journal.Sequence||appliedJournalSequence!=journal.Sequence)throw new InvalidOperationException("EXTERNAL_SAFETY_INTERLOCK_DENIED");}}
public sealed class UnavailableExternalLifecycleJournal:IExternalLifecycleJournal{private static InvalidOperationException Off()=>new("EXTERNAL_JOURNAL_NOT_CONFIGURED");public Task<JournalHighWater> ReadLinearizableAsync(string licenseId,CancellationToken ct)=>Task.FromException<JournalHighWater>(Off());public Task<JournalAppendResult?> FindByRequestAsync(string scope,string requestId,CancellationToken ct)=>Task.FromException<JournalAppendResult?>(Off());public Task<JournalAppendResult> ConditionalAppendAsync(JournalCommand command,CancellationToken ct)=>Task.FromException<JournalAppendResult>(Off());}
public sealed class UnavailableRestoreGateReader:IRestoreGateReader{public Task<RestoreGateState> ReadAuthoritativeAsync(CancellationToken ct)=>Task.FromResult(new RestoreGateState(false,"","",-1,false));}
