import fs from 'node:fs';
const [port,site,license,folder,boundLicense]=process.argv.slice(2);
const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
let targets;
for(let i=0;i<100;i++) {try{targets=await(await fetch(`http://127.0.0.1:${port}/json/list`)).json();if(targets.length)break;}catch{}await pause(100);}
if(!targets?.length)throw new Error('Chrome fixture did not start');
const socket=new WebSocket(targets.find(t=>t.type==='page').webSocketDebuggerUrl);
await new Promise((resolve,reject)=>{socket.onopen=resolve;socket.onerror=reject;});
let next=0;const waiting=new Map(),errors=[];
socket.onmessage=event=>{const data=JSON.parse(event.data);if(data.id){const p=waiting.get(data.id);waiting.delete(data.id);if(data.error)p.reject(new Error(data.error.message));else p.resolve(data.result);}else if(data.method==='Runtime.exceptionThrown')errors.push(data.params.exceptionDetails.text);};
const send=(method,params={})=>new Promise((resolve,reject)=>{const id=++next;waiting.set(id,{resolve,reject});socket.send(JSON.stringify({id,method,params}));});
const evaluate=async expression=>{const result=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true,userGesture:true});if(result.exceptionDetails)throw new Error('Browser evaluation failed');return result.result.value;};
const wait=async expression=>{for(let i=0;i<140;i++){if(await evaluate(expression))return;await pause(100);}throw new Error('UI state did not arrive: '+expression.slice(0,140));};
const check=(condition,message)=>{if(!condition)throw new Error(message);};
await send('Page.enable');await send('Runtime.enable');await send('Network.enable');
await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1100,deviceScaleFactor:1,mobile:false});
await send('Page.navigate',{url:site+'/fixture-login'});
await wait("document.title.includes('Licenças e aparelhos') && document.querySelector('[data-support]')");
check(await evaluate("document.querySelectorAll('.station-stats article').length===4"),'dashboard summary missing');
check(await evaluate("document.querySelector('tbody').innerText.includes('Atendimento de demonstração')"),'browser fixture absent');
check(await evaluate("document.querySelector('nav [aria-current]').textContent==='Códigos Station'"),'code access navigation unclear');
check(await evaluate("document.querySelector('.station-access-steps').children.length===3"),'code access guide missing');
await evaluate("document.querySelector('[data-find-client]').click()");
check(await evaluate("document.activeElement.id==='station-client-search' && !document.getElementById('station-confirm').open"),'header shortcut failed to focus client search');
await evaluate('scrollTo(0,0)');
const screenshot=async name=>{const p=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true});fs.writeFileSync(folder+'/'+name,Buffer.from(p.data,'base64'));};
await screenshot('station-panel-desktop.png');
await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
await pause(150);check(await evaluate('document.documentElement.scrollWidth<=innerWidth'),'mobile page overflows viewport');
check(await evaluate("[...document.querySelectorAll('[data-support]')].every(b=>{const r=b.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth})"),'mobile support buttons require horizontal scrolling');
check(await evaluate("[...document.querySelectorAll('[data-access-license]')].every(b=>{const r=b.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth})"),'mobile code buttons require horizontal scrolling');
await screenshot('station-panel-mobile.png');
await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1100,deviceScaleFactor:1,mobile:false});
await evaluate(`document.querySelector('[data-support="${license}"]').click()`);
await wait("document.querySelector('[data-action=\"issue-code\"]') && document.getElementById('station-support').open");
await screenshot('station-panel-support.png');
check(await evaluate("!document.querySelector('[data-action=\"new-device\"]')"),'pending license offers device transfer');
await evaluate("document.querySelector('#station-support [data-close]').click()");
const supportReads=await evaluate("performance.getEntriesByType('resource').filter(r=>r.name.includes('format=json&license=')).length");
await evaluate(`document.querySelector('[data-access-license="${license}"]').click()`);
await wait("document.getElementById('station-confirm').open");
check(await evaluate(`performance.getEntriesByType('resource').filter(r=>r.name.includes('format=json&license=')).length>${supportReads}`),'direct code action used stale list data');
check(await evaluate(`document.querySelector('[name=license_id]').value===${JSON.stringify(license)} && document.querySelector('[name=action]').value==='issue-code'`),'direct code action chose wrong license or operation');
check(await evaluate("document.getElementById('station-effect').textContent.includes('anterior')"),'rotation consequences missing');
await evaluate("document.querySelector('[name=password]').value='wrong-password';document.getElementById('station-submit').click()");
await wait("document.getElementById('station-action-error').textContent.includes('Senha administrativa incorreta') && !document.getElementById('station-submit').disabled");
check(await evaluate("document.getElementById('station-code').textContent===''") ,'wrong password revealed code');
await evaluate("document.querySelector('[name=password]').value='fixture-password';document.getElementById('station-submit').click()");
await wait("document.getElementById('station-issued').open && document.getElementById('station-code').textContent.length===43");
check(await evaluate("document.getElementById('station-code-delivery').textContent.includes('WhatsApp não solicitado')"),'delivery default is unsafe');
check(await evaluate("localStorage.length===0 && sessionStorage.length===0"),'code or UI data persisted in browser storage');
await evaluate("document.querySelector('#station-issued [data-close]').click()");
await wait("document.querySelector('[data-support]') && !document.getElementById('station-issued').open && document.getElementById('station-code').textContent===''");
const csrfGate=await evaluate(`(async()=>{const data=new FormData();data.set('license_id',${JSON.stringify(license)});data.set('action','issue-code');const response=await fetch('/admin/station?format=json',{method:'POST',body:data});return response.status;})()`);
check(csrfGate===419,'CSRF gate did not reject write');
await send('Page.navigate',{url:site+'/admin/station?q='+encodeURIComponent(boundLicense)});
await wait(`document.querySelector('[data-access-license="${boundLicense}"]')?.dataset.accessAction==='new-device'`);
check(await evaluate("!document.querySelector('[data-access-action=\"issue-code\"]')"),'bound license offers an ordinary activation code');
const boundBefore=await evaluate(`(async()=>{const r=await fetch('/admin/station?format=json&license='+${JSON.stringify(boundLicense)});return (await r.json()).license;})()`);
await evaluate(`document.querySelector('[data-access-license="${boundLicense}"]').click()`);
await wait("document.getElementById('station-confirm').open");
check(await evaluate(`document.querySelector('[name=action]').value==='new-device' && document.querySelector('[name=license_id]').value===${JSON.stringify(boundLicense)}`),'bound license shortcut chose wrong operation');
check(await evaluate("document.getElementById('station-effect').textContent.includes('anterior perde o acesso') && document.querySelector('[name=password]').value===''") ,'device replacement omitted consequences or password confirmation');
await evaluate("document.querySelector('#station-confirm [data-close]').click();document.querySelector('#station-support [data-close]').click()");
const boundAfter=await evaluate(`(async()=>{const r=await fetch('/admin/station?format=json&license='+${JSON.stringify(boundLicense)});return (await r.json()).license;})()`);
check(boundBefore.revocationGeneration===boundAfter.revocationGeneration && boundBefore.activationGeneration===boundAfter.activationGeneration && boundAfter.enrollmentState==='BOUND','cancelled replacement changed an existing device');
await send('Page.navigate',{url:site+'/admin'});
await wait("document.readyState==='complete' && document.querySelector('#inicio .page-heading a[href=\"/admin/station\"]')");
check(await evaluate("document.querySelector('aside a[href=\"/admin/station\"]').textContent.includes('Códigos Station')"),'main dashboard code navigation missing');
check(await evaluate("(()=>{const b=document.querySelector('.station-access-shortcut');const s=getComputedStyle(b);return b.getBoundingClientRect().height>=44&&s.textDecorationLine==='none'})()"),'main dashboard shortcut has no button styling');
await screenshot('station-dashboard-desktop.png');
await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
await pause(150);
check(await evaluate("(()=>{const r=document.querySelector('#inicio .page-heading a[href=\"/admin/station\"]').getBoundingClientRect();return r.width>0&&r.left>=0&&r.right<=innerWidth})()"),'main dashboard code shortcut overflows mobile');
await screenshot('station-dashboard-mobile.png');
await evaluate("document.querySelector('#inicio .page-heading a[href=\"/admin/station\"]').click()");
await wait("document.querySelector('[data-find-client]')");
check(errors.length===0,'browser script exception');
const evidence={desktopWidth:1440,mobileWidth:390,viewportOverflow:false,mobileSupportButtonVisible:true,mobileCodeButtonVisible:true,dashboardCodeShortcutVisible:true,dashboardNavigationWorks:true,searchShortcutFocused:true,directCodeConfirmed:true,directCodeFreshSupport:true,boundDeviceShortcutConfirmed:true,cancelledDeviceChangePreserved:true,adminPasswordRejected:true,csrfRejected:true,pendingTransferHidden:true,codeAppearsOnce:true,codeStorage:false,whatsappOptIn:true,browserExceptions:errors.length,credentialsIncluded:false};
fs.writeFileSync(folder+'/browser-validation.json',JSON.stringify(evidence,null,2)+'\n');
socket.close();console.log('STATION BROWSER: OK (desktop/mobile, code/search/device shortcuts, fresh support, cancelled replacement, action effects, admin password, CSRF, code visibility, no browser storage, WhatsApp opt-in)');
